import type { FloatingReaction, Meeting, Participant, ReactionName } from "@/lib/types";
import type { UserSettings } from "@/lib/types";

export interface MeetingRoomStageProps {
  code: string;
  meeting: Meeting | null;
  participants: Participant[];
  session: { participant: Participant; isVideoOn: boolean };
  elapsed: number;
  view: "speaker" | "gallery";
  onViewChange: (view: "speaker" | "gallery") => void;
  localStream: MediaStream | null;
  remoteStreams: Map<number, MediaStream>;
  reactions: Record<number, FloatingReaction>;
  mirrorLocalVideo: boolean;
  virtualBackground: UserSettings["virtual_background"];
  displayParticipantNames: boolean;
  speakerDeviceId: string;
  onAudioOutputError: (message: string) => void;
  confirmLeave: boolean;
  shareScreenAudio: boolean;
  screenStream: MediaStream | null;
  mediaError: string | null;
  permissionDismissed: boolean;
  onDismissPermissionError: () => void;
  isHost: boolean;
  endMenuOpen: boolean;
  unreadChatCount: number;
  chatEnabled: boolean;
  activePanel: string | null;
  onToggleMute: () => void;
  onToggleVideo: () => void;
  onToggleScreenShare: () => void;
  onOpenWhiteboard: () => void;
  onParticipants: () => void;
  onChat: () => void;
  onEndMenu: () => void;
  onEndMeeting: () => void;
  onLeave: () => void;
  onFeatureError: (message: string) => void;
  onMeetingChange: (meeting: Meeting) => void;
  onPanelClose: () => void;
  onUnreadChange: (count: number) => void;
  onLastMessageIdChange: (messageId: number) => void;
  onParticipantsChange: (participants: Participant[]) => void;
  onRemoved: () => void;
  onHostMute: (participant: Participant) => void;
  onLowerHand: (participant: Participant) => void;
  onReaction: (reaction: ReactionName) => void;
  onToggleHand: () => void;
}
