"""Application-wide values shared by configuration and services."""

DEFAULT_USER_ID = 1
DEFAULT_USER_NAME = "Zoom User"
DEFAULT_USER_EMAIL = "user@example.com"
DEFAULT_AVATAR_COLOR = "#0B5CFF"
JWT_EXPIRY_HOURS = 24
DEFAULT_MEETING_DURATION_MINUTES = 40
MIN_MEETING_DURATION_MINUTES = 5
MAX_MEETING_DURATION_MINUTES = 1440
MAX_MEETING_TITLE_LENGTH = 200
MAX_MEETING_DESCRIPTION_LENGTH = 2000
MEETING_CODE_LENGTH = 11
DEFAULT_MEETING_TIMEZONE = "UTC"
MAX_MEETING_TIMEZONE_LENGTH = 64
MAX_CHAT_MESSAGE_LENGTH = 1000
